# Generated by Django 5.2.9 on 2026-01-28 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_alter_schoolclass_name_alter_student_school_class'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Комментарий'),
        ),
    ]
